name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --clean --noconsole --onefile --name SnapMemoriesDL ^
            --add-binary "bin\\ffmpeg.exe;bin" --add-binary "bin\\ffprobe.exe;bin" snap_memories_dl.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SnapMemoriesDL
          path: dist/SnapMemoriesDL.exe

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SnapMemoriesDL.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

